refactoring of bin/cli(.php) and index.php symlink
The `bin/cli` and `bin/cli.php` may become symlinks as well in the future
depending on how we want to do this.

The Honeybee\Core\Environment class may need to be adjusted or removed
according to the environaut integration we want.

refs #21457

diff --git a/applications/cms/bin/cli b/applications/cms/bin/cli
--- a/applications/cms/bin/cli
+++ b/applications/cms/bin/cli
@@ -3,23 +3,25 @@
 LOCAL_CONFIG_SH=`dirname $0`/../etc/local/config.sh
 
 if [ -f $LOCAL_CONFIG_SH ] ; then
-  echo "[INFO] Found and sourcing the config.sh"
-  . $LOCAL_CONFIG_SH
+    echo "[INFO] Sourcing local config file: $LOCAL_CONFIG_SH"
+    . $LOCAL_CONFIG_SH
 else
-  echo "[ERROR] Could not source $LOCAL_CONFIG_SH!"
-  echo "Make sure to run bin/configure-env before doing anything else after a fresh checkout"
+    echo "[ERROR] Couldn't source local config: $LOCAL_CONFIG_SH"
+    echo "[ERROR] Make sure to run 'make configure' or 'make reconfigure'."
+    exit 1
 fi
 
-if (test -z "$PHP_COMMAND") ; then
-  echo "[ERROR] Unable to find a valid php command!"
-  echo "Have you run bin/configure-env.php allready?"
-  exit 0
+if [ -z "$PHP_COMMAND" ] ; then
+    echo "[ERROR] Unable to find a valid php executable."
+    echo "[ERROR] Make sure to run 'make configure' or 'make reconfigure'."
+    exit 1
 fi
 
 if [ -z "$AGAVI_ENVIRONMENT" ] ; then
-    echo "[Executing] `which rlwrap` $PHP_COMMAND -d html_errors=off -f `dirname $0`/cli.php $@"
-    PHP_COMMAND=$PHP_COMMAND `which rlwrap` $PHP_COMMAND -d html_errors=off -f "`dirname $0`/cli.php" -- "$@"
-else
-    echo "[Executing] `which rlwrap` $AGAVI_ENVIRONMENT $PHP_COMMAND -d html_errors=off -f `dirname $0`/cli.php $@"
-    PHP_COMMAND=$PHP_COMMAND AGAVI_ENVIRONMENT=$AGAVI_ENVIRONMENT $PHP_COMMAND -d html_errors=off -f "`dirname $0`/cli.php" -- "$@"
+    echo "[ERROR] AGAVI_ENVIRONMENT is not set."
+    echo "[ERROR] Make sure to run 'make configure' or 'make reconfigure'."
+    exit 1
 fi
+
+echo "[INFO] Executing: `which rlwrap` $AGAVI_ENVIRONMENT $PHP_COMMAND -d html_errors=off -f `dirname $0`/cli.php $@"
+PHP_COMMAND=$PHP_COMMAND AGAVI_ENVIRONMENT=$AGAVI_ENVIRONMENT $PHP_COMMAND -d html_errors=off -f "`dirname $0`/cli.php" -- "$@"
